### ISSUE TITLE
ogg_pager: test fails

### ISSUE THREAD

**Issue by tenzap** [Serial-ATA/lofty-rs#150]
### Summary

$ cargo test
```
    Updating crates.io index
   Compiling byteorder v1.4.3
   Compiling ogg_pager v0.5.0 (/mnt/packages/git_repos/dpkg/debcargo-conf/build/ogg-pager)
    Finished test [unoptimized + debuginfo] target(s) in 1.91s
     Running unittests src/lib.rs (target/debug/deps/ogg_pager-e2195aa5bf33c666)

running 2 tests
test tests::paginate_large ... FAILED
test tests::opus_ident_header ... FAILED

failures:

---- tests::paginate_large stdout ----
thread 'tests::paginate_large' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:224:77

---- tests::opus_ident_header stdout ----
thread 'tests::opus_ident_header' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/lib.rs:215:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::opus_ident_header
    tests::paginate_large

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--lib`
```

**Comment by Serial-ATA** [comment]
Assuming this is related to #157, reopen if not.
