### ISSUE TITLE
Hound's test samples not working.

### ISSUE THREAD

**Issue by sagudev** [Serial-ATA/lofty-rs#32]
I tried test samples from [hound](https://github.com/ruuda/hound) and none of it was read successfully using examples/tag_reader.

Here is log from terminal:
```
------------Processing /home/user/Prejemi/hound-master/testsamples/nonstandard-01.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/nonstandard-02.wav file..
thread 'main' panicked at 'Error: Failed to read file!: Wav("Extensible format identified, invalid \"fmt \" chunk size found (< 40)")', examples/tag_reader.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/pcmwaveformat-16bit-44100Hz-mono-extra.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/pcmwaveformat-16bit-44100Hz-mono.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/pcmwaveformat-24bit-4byte-48kHz-stereo.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/pcmwaveformat-8bit-44100Hz-mono.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/pop.wav file..
thread 'main' panicked at 'Error: Failed to read file!: Wav("Extensible format identified, invalid \"fmt \" chunk size found (< 40)")', examples/tag_reader.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatex-16bit-44100Hz-mono-extra.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatex-16bit-44100Hz-mono.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatex-16bit-44100Hz-stereo.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatex-8bit-11025Hz-mono.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatex-ieeefloat-44100Hz-mono.wav file..
thread 'main' panicked at 'attempt to divide by zero', src/iff/wav/properties.rs:165:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatextensible-24bit-192kHz-mono.wav file..
thread 'main' panicked at 'Error: Failed to read file!: Wav("Extensible format identified, invalid \"fmt \" chunk size found (< 40)")', examples/tag_reader.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatextensible-24bit-4byte-48kHz-stereo.wav file..
thread 'main' panicked at 'Error: Failed to read file!: Wav("Extensible format identified, invalid \"fmt \" chunk size found (< 40)")', examples/tag_reader.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatextensible-32bit-48kHz-stereo.wav file..
thread 'main' panicked at 'Error: Failed to read file!: Wav("Extensible format identified, invalid \"fmt \" chunk size found (< 40)")', examples/tag_reader.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
------------Processing /home/user/Prejemi/hound-master/testsamples/waveformatextensible-ieeefloat-44100Hz-mono.wav file..
thread 'main' panicked at 'Error: Failed to read file!: Wav("Extensible format identified, invalid \"fmt \" chunk size found (< 40)")', examples/tag_reader.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sagudev** [comment]
In [my fork](https://github.com/sagudev/lofty-rs/tree/wave-depth) I already have fixes awaiting built on top of #31.

**Comment by Serial-ATA** [comment]
Ah, thanks for testing this out. The properties side of lofty isn't all that robust :)

Were you able to resolve all of the errors?

**Comment by sagudev** [comment]
Yes, but with sacrifice for some readability.

**Comment by Serial-ATA** [comment]
That's alright. Just be sure to throw in some comments if it gets too bad.
