### ISSUE TITLE
Panic `attempt to divide by zero` when reading properties of music file

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#43]
Probably simple reading tags from file 

https://github.com/qarmin/czkawka/blob/dd103b9520063dd653ff54230957e89eb23a00c0/czkawka_core/src/same_music.rs#L365-L371

crashes app with backtrace
```
thread '<unnamed>' panicked at 'attempt to divide by zero', /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/properties.rs:513:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: lofty::mp4::properties::mp4a_properties
   4: lofty::mp4::properties::read_properties
   5: lofty::mp4::read::read_from
   6: lofty::probe::read_from_path
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   8: rayon::iter::plumbing::Folder::consume_iter
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: <rayon::vec::IntoIter<T> as rayon::iter::IndexedParallelIterator>::with_producer
  11: rayon::iter::plumbing::bridge
  12: rayon::iter::from_par_iter::<impl rayon::iter::FromParallelIterator<T> for alloc::vec::Vec<T>>::from_par_iter
  13: czkawka_core::same_music::SameMusic::find_same_music
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
[sample (1 307th copy)80.m4a.zip](https://github.com/Serial-ATA/lofty-rs/files/8592161/sample.1.307th.copy.80.m4a.zip)

**Comment by Serial-ATA** [comment]
Thanks! Fixed in https://github.com/Serial-ATA/lofty-rs/commit/caf043a3a25a0b3ba765aa944b6c8bba10ee8acd
