### ISSUE TITLE
Panic with custom type

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#438]
### Reproducer

```
const ALL_FILE_TYPES: &[FileType] = &[FileType::Aac, FileType::Aiff, FileType::Ape, FileType::Flac, FileType::Mpeg, FileType::Mp4, FileType::Mpc, FileType::Opus, FileType::Vorbis, FileType::Speex, FileType::Wav, FileType::WavPack, FileType::Custom("custom")];

fn check_file(path: &str) {
    let content = match fs::read(&path) {
        Ok(content) => content,
        Err(e) => {
            println!("{e} - {path}");
            return;
        }
    };

    for i in ALL_FILE_TYPES {
        let s = std::io::Cursor::new(&content);
        let tagged_file = match Probe::with_file_type(s, *i).read() {
            Ok(t) => t,
            Err(_e) => {
                continue;
            }
        };
        tagged_file.properties();
        tagged_file.tags();
        tagged_file.primary_tag();
    }
}

```

### Summary

```
 thread '<unnamed>' panicked at /home/runner/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/resolve.rs:50:5:
Encountered an unregistered custom `FileType` named `custom`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/612a33f20b9b2c27380edbc4b26a01433ed114bc/library/core/src/panicking.rs:74:14
   2: lofty::resolve::lookup_resolver
             at /home/runner/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/resolve.rs:50:2
   3: lofty::probe::Probe<R>::read
             at /home/runner/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/probe.rs:485:21
```

### Expected behavior

No panic - just error

**Comment by Serial-ATA** [comment]
Hello!

Unregistered resolvers are meant to panic, they have to be registered prior to calling `Probe::read()`. See [here](https://github.com/Serial-ATA/lofty-rs/tree/main/examples/custom_resolver) for an example.
