### ISSUE TITLE
Attempt to subtract with overflow when reading file

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#439]
### Reproducer

```
const ALL_FILE_TYPES: &[FileType] = &[FileType::Aac, FileType::Aiff, FileType::Ape, FileType::Flac, FileType::Mpeg, FileType::Mp4, FileType::Mpc, FileType::Opus, FileType::Vorbis, FileType::Speex, FileType::Wav, FileType::WavPack];

fn check_file(path: &str) {
    let content = match fs::read(&path) {
        Ok(content) => content,
        Err(e) => {
            println!("{e} - {path}");
            return;
        }
    };

    for i in ALL_FILE_TYPES {
        let s = std::io::Cursor::new(&content);
        let tagged_file = match Probe::with_file_type(s, *i).read() {
            Ok(t) => t,
            Err(_e) => {
                continue;
            }
        };
        tagged_file.properties();
        tagged_file.tags();
        tagged_file.primary_tag();
    }
}
```

### Summary

```
thread 'main' panicked at /home/rafal/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/aac/read.rs:49:5:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/panicking.rs:181:21
   3: lofty::aac::read::read_from
             at /home/rafal/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/aac/read.rs:49:5
   4: <lofty::aac::AacFile as lofty::file::audio_file::AudioFile>::read_from
             at /home/rafal/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/aac/mod.rs:19:10
   5: lofty::probe::Probe<R>::read
             at /home/rafal/.cargo/git/checkouts/lofty-rs-f5e48f8219b271cf/1505ddf/lofty/src/probe.rs:468:22
   6: lofty::check_file
             at /home/rafal/Projekty/Rust/run_command_for_every_file/src/crates/lofty/src/main.rs:42:33
   7: lofty::main
             at /home/rafal/Projekty/Rust/run_command_for_every_file/src/crates/lofty/src/main.rs:27:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/7120fdac7a6e55a5e4b606256042890b36067052/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```

### Assets

[crash-b4fbdd81f703dccc64a529a646921b27ccb56b4a.zip](https://github.com/user-attachments/files/16433414/crash-b4fbdd81f703dccc64a529a646921b27ccb56b4a.zip)

**Comment by qarmin** [comment]
Even 10 bytes file cause same problems - [compressed.zip](https://github.com/user-attachments/files/16436510/compressed.zip)

**Comment by Serial-ATA** [comment]
Thanks, the second input actually causes a separate issue, but they're both related.
