### ISSUE TITLE
Freeze when trying to read properties 

### ISSUE THREAD

**Issue by qarmin** [Serial-ATA/lofty-rs#44]
Library completely freeze when trying to execute 
```
    lofty::read_from_path(
        Path::new("/home/rafal/Downloads/Czkawka.glitch.files/14 To The Wild.m4a"),
        true,
    );
```

on provided files
[Czkawka.glitch.files.zip](https://github.com/Serial-ATA/lofty-rs/files/8592482/Czkawka.glitch.files.zip)

GDB backtraces
```
#0  0x00007ffff7d8d932 in __GI___libc_read (fd=3, buf=0x5555556c3bf0, nbytes=8192) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x00005555556448f6 in std::sys::unix::fd::FileDesc::read_buf () at library/std/src/sys/unix/fd.rs:120
#2  std::sys::unix::fs::File::read_buf () at library/std/src/sys/unix/fs.rs:896
#3  std::fs::{impl#5}::read_buf () at library/std/src/fs.rs:628
#4  0x000055555557ce8b in std::io::buffered::bufreader::{impl#4}::fill_buf<std::fs::File> (self=0x7fffffffd710) at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/buffered/bufreader.rs:389
#5  0x000055555557cafc in std::io::buffered::bufreader::{impl#3}::read<std::fs::File> (self=0x7fffffffd710, buf=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/buffered/bufreader.rs:267
#6  0x0000555555571d3c in std::io::default_read_exact<std::io::buffered::bufreader::BufReader<std::fs::File>> (this=0x7fffffffd710, buf=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:450
#7  0x000055555557cd7f in std::io::buffered::bufreader::{impl#3}::read_exact<std::fs::File> (self=0x7fffffffd710, buf=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/buffered/bufreader.rs:304
#8  0x000055555557c573 in byteorder::io::ReadBytesExt::read_u32<std::io::buffered::bufreader::BufReader<std::fs::File>, byteorder::BigEndian> (self=0x7fffffffd710)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/io.rs:219
#9  0x0000555555572200 in lofty::mp4::atom_info::AtomInfo::read<std::io::buffered::bufreader::BufReader<std::fs::File>> (data=0x7fffffffd710)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/atom_info.rs:48
#10 0x000055555557f180 in lofty::mp4::moov::Moov::parse<std::io::buffered::bufreader::BufReader<std::fs::File>> (data=0x7fffffffd710, read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/moov.rs:52
#11 0x0000555555580da5 in lofty::mp4::read::read_from<std::io::buffered::bufreader::BufReader<std::fs::File>> (data=0x7fffffffd710, read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/read.rs:45
#12 0x0000555555590ef6 in lofty::mp4::{impl#1}::read_from<std::io::buffered::bufreader::BufReader<std::fs::File>> (reader=0x7fffffffd710, read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/mod.rs:76
#13 0x00005555555933d1 in lofty::probe::Probe<std::io::buffered::bufreader::BufReader<std::fs::File>>::read<std::io::buffered::bufreader::BufReader<std::fs::File>> (self=..., read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/probe.rs:228
#14 0x000055555559452a in lofty::probe::read_from_path<&std::path::Path> (path=..., read_properties=true) at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/probe.rs:264
#15 0x0000555555597a58 in camel_to_big_case::loftyy () at src/main.rs:16
#16 0x00005555555979eb in camel_to_big_case::main () at src/main.rs:11

```

```
#0  0x0000555555612e53 in core::cmp::min_by<usize, fn(&usize, &usize) -> core::cmp::Ordering> (v1=4, v2=8, compare=0x4) at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/cmp.rs:1218
#1  0x0000555555612db4 in core::cmp::Ord::min<usize> (self=4, other=8) at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/cmp.rs:820
#2  0x0000555555612de4 in core::cmp::min<usize> (v1=4, v2=8) at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/cmp.rs:1199
#3  0x000055555557cf7c in std::io::buffered::bufreader::{impl#4}::consume<std::fs::File> (self=0x7fffffffd710, amt=4)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/buffered/bufreader.rs:400
#4  0x000055555557ccbd in std::io::buffered::bufreader::{impl#3}::read<std::fs::File> (self=0x7fffffffd710, buf=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/buffered/bufreader.rs:270
#5  0x0000555555571d3c in std::io::default_read_exact<std::io::buffered::bufreader::BufReader<std::fs::File>> (this=0x7fffffffd710, buf=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:450
#6  0x000055555557cd7f in std::io::buffered::bufreader::{impl#3}::read_exact<std::fs::File> (self=0x7fffffffd710, buf=...)
    at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/buffered/bufreader.rs:304
#7  0x000055555557c573 in byteorder::io::ReadBytesExt::read_u32<std::io::buffered::bufreader::BufReader<std::fs::File>, byteorder::BigEndian> (self=0x7fffffffd710)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.4.3/src/io.rs:219
#8  0x0000555555572200 in lofty::mp4::atom_info::AtomInfo::read<std::io::buffered::bufreader::BufReader<std::fs::File>> (data=0x7fffffffd710)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/atom_info.rs:48
#9  0x000055555557f180 in lofty::mp4::moov::Moov::parse<std::io::buffered::bufreader::BufReader<std::fs::File>> (data=0x7fffffffd710, read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/moov.rs:52
#10 0x0000555555580da5 in lofty::mp4::read::read_from<std::io::buffered::bufreader::BufReader<std::fs::File>> (data=0x7fffffffd710, read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/read.rs:45
#11 0x0000555555590ef6 in lofty::mp4::{impl#1}::read_from<std::io::buffered::bufreader::BufReader<std::fs::File>> (reader=0x7fffffffd710, read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/mp4/mod.rs:76
#12 0x00005555555933d1 in lofty::probe::Probe<std::io::buffered::bufreader::BufReader<std::fs::File>>::read<std::io::buffered::bufreader::BufReader<std::fs::File>> (self=..., read_properties=true)
    at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/probe.rs:228
#13 0x000055555559452a in lofty::probe::read_from_path<&std::path::Path> (path=..., read_properties=true) at /home/rafal/.cargo/registry/src/github.com-1ecc6299db9ec823/lofty-0.6.2/src/probe.rs:264
#14 0x0000555555597a58 in camel_to_big_case::loftyy () at src/main.rs:16
#15 0x00005555555979eb in camel_to_big_case::main () at src/main.rs:11

```

**Comment by Serial-ATA** [comment]
Thanks for all the details! It's been fixed in https://github.com/Serial-ATA/lofty-rs/commit/679cac6173cbfc28072258c0ce95cfb87b2c2d8c :)
